apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hub
spec:
  containers:
    - name: node
      image: bearerhub/node-10.9:0.6
      command:
        - cat
      tty: true
  volumes:
    - name: docker-socket-volume
      empty: {}
