/** Declaration file generated by dts-gen */

declare class IdtokenVerifier {
  constructor(parameters: any);

  decode(token: any): any

  getRsaVerifier(iss: any, kid: any, cb: any): any

  validateAccessToken(accessToken: any, alg: any, atHash: any, cb: any): any

  verify(token: any, nonce: any, cb: any): any

  verifyExpAndIat(exp: any, iat: any): any

  verifyExpAndNbf(exp: any, nbf: any): any
}

declare namespace idtoken_verifier {
  namespace prototype {
    function decode(token: any): any

    function getRsaVerifier(iss: any, kid: any, cb: any): any

    function validateAccessToken(
      accessToken: any,
      alg: any,
      atHash: any,
      cb: any
    ): any

    function verify(token: any, nonce: any, cb: any): any

    function verifyExpAndIat(exp: any, iat: any): any

    function verifyExpAndNbf(exp: any, nbf: any): any

    namespace decode {
      const prototype: {}
    }

    namespace getRsaVerifier {
      const prototype: {}
    }

    namespace validateAccessToken {
      const prototype: {}
    }

    namespace verify {
      const prototype: {}
    }

    namespace verifyExpAndIat {
      const prototype: {}
    }

    namespace verifyExpAndNbf {
      const prototype: {}
    }
  }
}

declare module "idtoken-verifier" {
  export = IdtokenVerifier
}
